/*
 * THIS FILE IS AUTO-GENERATED. ANY EDITS MAY BE LOST.
 *
 * Make changes to: atmega8.avrspec
 *
 * Pin configuration for atmega8.
 */
#if	defined(__AVR_ATmega8__)

#include <stdint.h>
#include <avr/io.h>
#include <avr/pgmspace.h>

#include "gpio_private.h"


uint8_t			_gpio_adc_reference = 0;

const gpio_timer_t PROGMEM	_gpio_timers[] =
{
	/* timer_1A */
	{
#ifndef	WITHOUT_HIRES_TIMERS
		GPIO_TIMER_TYPE_16BIT,
#endif
		REG_TO_OFFSET(TCCR1A),
		(uint8_t) ~((1<<COM1A1)|(1<<COM1A0)),
		(1<<COM1A1),
		REG_TO_OFFSET(OCR1A)
	},
	/* timer_1B */
	{
#ifndef	WITHOUT_HIRES_TIMERS
		GPIO_TIMER_TYPE_16BIT,
#endif
		REG_TO_OFFSET(TCCR1A),
		(uint8_t) ~((1<<COM1B1)|(1<<COM1B0)),
		(1<<COM1B1),
		REG_TO_OFFSET(OCR1B)
	}
};


const struct _gpio_pin PROGMEM	_gpio_pins[GPIO_PIN_COUNT] =
{
	/* #0 - D0 (PD0) */
	{
		REG_TO_OFFSET(DDRD),
		REG_TO_OFFSET(PORTD),
		REG_TO_OFFSET(PIND),
		(1 << 0), /* DDRD0/PORTD0/PIND0 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #1 - D1 (PD1) */
	{
		REG_TO_OFFSET(DDRD),
		REG_TO_OFFSET(PORTD),
		REG_TO_OFFSET(PIND),
		(1 << 1), /* DDRD1/PORTD1/PIND1 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #2 - D2 (PD2) */
	{
		REG_TO_OFFSET(DDRD),
		REG_TO_OFFSET(PORTD),
		REG_TO_OFFSET(PIND),
		(1 << 2), /* DDRD2/PORTD2/PIND2 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #3 - D3 (PD3) */
	{
		REG_TO_OFFSET(DDRD),
		REG_TO_OFFSET(PORTD),
		REG_TO_OFFSET(PIND),
		(1 << 3), /* DDRD3/PORTD3/PIND3 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #4 - D4 (PD4) */
	{
		REG_TO_OFFSET(DDRD),
		REG_TO_OFFSET(PORTD),
		REG_TO_OFFSET(PIND),
		(1 << 4), /* DDRD4/PORTD4/PIND4 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #5 - D5 (PD5) */
	{
		REG_TO_OFFSET(DDRD),
		REG_TO_OFFSET(PORTD),
		REG_TO_OFFSET(PIND),
		(1 << 5), /* DDRD5/PORTD5/PIND5 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #6 - D6 (PD6) */
	{
		REG_TO_OFFSET(DDRD),
		REG_TO_OFFSET(PORTD),
		REG_TO_OFFSET(PIND),
		(1 << 6), /* DDRD6/PORTD6/PIND6 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #7 - D7 (PD7) */
	{
		REG_TO_OFFSET(DDRD),
		REG_TO_OFFSET(PORTD),
		REG_TO_OFFSET(PIND),
		(1 << 7), /* DDRD7/PORTD7/PIND7 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #8 - D8 (PB0) */
	{
		REG_TO_OFFSET(DDRB),
		REG_TO_OFFSET(PORTB),
		REG_TO_OFFSET(PINB),
		(1 << 0), /* DDRB0/PORTB0/PINB0 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #9 - D9 (PB1/OC1A) */
	{
		REG_TO_OFFSET(DDRB),
		REG_TO_OFFSET(PORTB),
		REG_TO_OFFSET(PINB),
		(1 << 1), /* DDRB1/PORTB1/PINB1 */
		GPIO_NO_ADC,
#ifndef	WITHOUT_HIRES_TIMERS
		0 /* timer_1A */
#else
		GPIO_NO_TIMER
#endif
	},

	/* #10 - D10 (PB2/OC1B) */
	{
		REG_TO_OFFSET(DDRB),
		REG_TO_OFFSET(PORTB),
		REG_TO_OFFSET(PINB),
		(1 << 2), /* DDRB2/PORTB2/PINB2 */
		GPIO_NO_ADC,
#ifndef	WITHOUT_HIRES_TIMERS
		1 /* timer_1B */
#else
		GPIO_NO_TIMER
#endif
	},

	/* #11 - D11 (PB3) */
	{
		REG_TO_OFFSET(DDRB),
		REG_TO_OFFSET(PORTB),
		REG_TO_OFFSET(PINB),
		(1 << 3), /* DDRB3/PORTB3/PINB3 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #12 - D12 (PB4) */
	{
		REG_TO_OFFSET(DDRB),
		REG_TO_OFFSET(PORTB),
		REG_TO_OFFSET(PINB),
		(1 << 4), /* DDRB4/PORTB4/PINB4 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #13 - D13 (PB5) */
	{
		REG_TO_OFFSET(DDRB),
		REG_TO_OFFSET(PORTB),
		REG_TO_OFFSET(PINB),
		(1 << 5), /* DDRB5/PORTB5/PINB5 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #14 - D14/A0 (PC0/ADC0) */
	{
		REG_TO_OFFSET(DDRC),
		REG_TO_OFFSET(PORTC),
		REG_TO_OFFSET(PINC),
		(1 << 0), /* DDRC0/PORTC0/PINC0 */
		0,
		GPIO_NO_TIMER
	},

	/* #15 - D15/A1 (PC1/ADC1) */
	{
		REG_TO_OFFSET(DDRC),
		REG_TO_OFFSET(PORTC),
		REG_TO_OFFSET(PINC),
		(1 << 1), /* DDRC1/PORTC1/PINC1 */
		1,
		GPIO_NO_TIMER
	},

	/* #16 - D16/A2 (PC2/ADC2) */
	{
		REG_TO_OFFSET(DDRC),
		REG_TO_OFFSET(PORTC),
		REG_TO_OFFSET(PINC),
		(1 << 2), /* DDRC2/PORTC2/PINC2 */
		2,
		GPIO_NO_TIMER
	},

	/* #17 - D17/A3 (PC3/ADC3) */
	{
		REG_TO_OFFSET(DDRC),
		REG_TO_OFFSET(PORTC),
		REG_TO_OFFSET(PINC),
		(1 << 3), /* DDRC3/PORTC3/PINC3 */
		3,
		GPIO_NO_TIMER
	},

	/* #18 - D18/A4 (PC4/ADC4) */
	{
		REG_TO_OFFSET(DDRC),
		REG_TO_OFFSET(PORTC),
		REG_TO_OFFSET(PINC),
		(1 << 4), /* DDRC4/PORTC4/PINC4 */
		4,
		GPIO_NO_TIMER
	},

	/* #19 - D19/A5 (PC5/ADC5) */
	{
		REG_TO_OFFSET(DDRC),
		REG_TO_OFFSET(PORTC),
		REG_TO_OFFSET(PINC),
		(1 << 5), /* DDRC5/PORTC5/PINC5 */
		5,
		GPIO_NO_TIMER
	},

	/* #20 - A6 (ADC6) */
	{
		GPIO_NO_REGISTER,
		GPIO_NO_REGISTER,
		GPIO_NO_REGISTER,
		0,
		6,
		GPIO_NO_TIMER
	},

	/* #21 - A7 (ADC7) */
	{
		GPIO_NO_REGISTER,
		GPIO_NO_REGISTER,
		GPIO_NO_REGISTER,
		0,
		7,
		GPIO_NO_TIMER
	},

	/* #22 - D22 (PC6) */
	{
		REG_TO_OFFSET(DDRC),
		REG_TO_OFFSET(PORTC),
		REG_TO_OFFSET(PINC),
		(1 << 6), /* DDRC6/PORTC6/PINC6 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
	},

	/* #23 - D23 (PB6/TOSC1) */
	{
#if	defined(WITHOUT_CRYSTAL_OSCILLATOR)
		REG_TO_OFFSET(DDRB),
		REG_TO_OFFSET(PORTB),
		REG_TO_OFFSET(PINB),
		(1 << 6), /* DDRB6/PORTB6/PINB6 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
#else	/* WITHOUT_CRYSTAL_OSCILLATOR */
		GPIO_NO_REGISTER,
		GPIO_NO_REGISTER,
		GPIO_NO_REGISTER,
		0,
		GPIO_NO_ADC,
		GPIO_NO_TIMER
#endif	/* WITHOUT_CRYSTAL_OSCILLATOR */
	},

	/* #24 - D24 (PB7/TOSC2) */
	{
#if	defined(WITHOUT_CRYSTAL_OSCILLATOR)
		REG_TO_OFFSET(DDRB),
		REG_TO_OFFSET(PORTB),
		REG_TO_OFFSET(PINB),
		(1 << 7), /* DDRB7/PORTB7/PINB7 */
		GPIO_NO_ADC,
		GPIO_NO_TIMER
#else	/* WITHOUT_CRYSTAL_OSCILLATOR */
		GPIO_NO_REGISTER,
		GPIO_NO_REGISTER,
		GPIO_NO_REGISTER,
		0,
		GPIO_NO_ADC,
		GPIO_NO_TIMER
#endif	/* WITHOUT_CRYSTAL_OSCILLATOR */
	}
};


const uint8_t PROGMEM		_gpio_analog_to_digital_pins[GPIO_ANALOG_PIN_COUNT] =
{
	14,	/* A0 -> D14 */
	15,	/* A1 -> D15 */
	16,	/* A2 -> D16 */
	17,	/* A3 -> D17 */
	18,	/* A4 -> D18 */
	19,	/* A5 -> D19 */
	20,	/* A6 */
	21	/* A7 */
};

#endif	/* __AVR_ATmega8__ */
